### ISSUE TITLE
erro ao executar null pointer

### ISSUE THREAD

**Issue by Danillosdd** [PHPJasper/phpjasper-laravel#23]
Exception in thread "main" net.sf.jasperreports.engine.JRRuntimeException: Error initializing graphic environment.
        at net.sf.jasperreports.engine.util.JRGraphEnvInitializer.initializeGraphEnv(JRGraphEnvInitializer.java:63)
        at net.sf.jasperreports.engine.fill.BaseReportFiller.<init>(BaseReportFiller.java:136)
        at net.sf.jasperreports.engine.fill.JRBaseFiller.<init>(JRBaseFiller.java:273)
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.<init>(JRVerticalFiller.java:79)
        at net.sf.jasperreports.engine.fill.JRFiller.createBandReportFiller(JRFiller.java:251)
        at net.sf.jasperreports.engine.fill.JRFiller.createReportFiller(JRFiller.java:272)
        at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:114)
        at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:103)
        at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:530)
        at net.sf.jasperreports.engine.JasperFillManager.fillReport(JasperFillManager.java:954)
        at de.cenote.jasperstarter.Report.fillInternal(Report.java:338)
        at de.cenote.jasperstarter.Report.fill(Report.java:282)
        at de.cenote.jasperstarter.App.processReport(App.java:226)
        at de.cenote.jasperstarter.App.main(App.java:109)
Caused by: java.lang.NullPointerException
        at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
        at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
        at sun.awt.FontConfiguration.init(FontConfiguration.java:107)
        at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)
        at sun.font.SunFontManager$2.run(SunFontManager.java:431)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.font.SunFontManager.<init>(SunFontManager.java:376)
        at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
        at sun.awt.X11FontManager.<init>(X11FontManager.java:57)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
        at sun.java2d.SunGraphicsEnvironment.getFontManagerForSGE(SunGraphicsEnvironment.java:190)
        at sun.java2d.SunGraphicsEnvironment.getAvailableFontFamilyNames(SunGraphicsEnvironment.java:224)
        at sun.java2d.SunGraphicsEnvironment.getAvailableFontFamilyNames(SunGraphicsEnvironment.java:252)
        at sun.java2d.HeadlessGraphicsEnvironment.getAvailableFontFamilyNames(HeadlessGraphicsEnvironment.java:94)
        at net.sf.jasperreports.engine.util.JRGraphEnvInitializer.initializeGraphEnv(JRGraphEnvInitializer.java:58)
        ... 13 more

**Comment by cr998** [comment]
It looks like you dont have font installed in your OS

Caused by: java.lang.NullPointerException
at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)

**Comment by adrianarboleda** [comment]
I have the exact same problem, did you find a solution?

**Comment by Danillosdd** [comment]
It's been a while, but at the time my Linux didn't recognize the font installed in the report, I ended up switching to a standard one.

**Comment by fenixlojo** [comment]
> 

Hey man! How did you change the font? Did you use Jaspersoft Studio to do it? If so , what font did you pick?
