### ISSUE TITLE
Getting "Unsupported major.minor version 52.0" error

### ISSUE THREAD

**Issue by hondaman900** [PHPJasper/phpjasper-laravel#9]
I'm getting what looks like a Java version error (`java.lang.UnsupportedClassVersionError`). I have Java SDK 10 installed, everything else looks good, but I keep getting this error and no report file generated. I tried the commands for the hello-world example directly in Tinker just to get something to function, and get this verbose error (I've included the Tinker command lines at the top before the error):

```
Psy Shell v0.8.17 (PHP 7.1.10 — cli) by Justin Hileman
>>> require __DIR__ . '/vendor/autoload.php';
=> Composer\Autoload\ClassLoader {#1}
>>> use PHPJasper\PHPJasper;
>>> $input = __DIR__ . '/vendor/geekcom/phpjasper-laravel/examples/hello_world.jasper';
=> "C:\xampp\htdocs\DS_dev_02/vendor/geekcom/phpjasper-laravel/examples/hello_world.jasper"
>>> $output = __DIR__ . '/vendor/geekcom/phpjasper-laravel/examples';
=> "C:\xampp\htdocs\DS_dev_02/vendor/geekcom/phpjasper-laravel/examples"
>>> $options = [
...     'format' => ['pdf', 'rtf']
... ];
=> [
     "format" => [
       "pdf",
       "rtf",
     ],
   ]
>>> $jasper = new PHPJasper;
=> PHPJasper\PHPJasper {#1179}
>>> $jasper->process(
...     $input,
...     $output,
...     $options
... )->execute();
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/sf/jasperreports/functions/standard/MathFunctions : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at net.sf.jasperreports.engine.util.JRClassLoader.loadClassForRealName(JRClassLoader.java:156)
        at net.sf.jasperreports.engine.util.JRClassLoader.loadClassForName(JRClassLoader.java:114)
        at net.sf.jasperreports.functions.FunctionsBundle.addFunctionClass(FunctionsBundle.java:83)
        at net.sf.jasperreports.functions.FunctionsBundle.<init>(FunctionsBundle.java:53)
        at net.sf.jasperreports.functions.FunctionsRegistryFactory.createRegistry(FunctionsRegistryFactory.java:73)
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.instantiateRegistry(DefaultExtensionsRegistry.java:295)
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.loadRegistries(DefaultExtensionsRegistry.java:270)
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.loadRegistries(DefaultExtensionsRegistry.java:190)
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.getRegistries(DefaultExtensionsRegistry.java:153)
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.getExtensions(DefaultExtensionsRegistry.java:125)
        at net.sf.jasperreports.engine.util.JRStyledTextParser.<clinit>(JRStyledTextParser.java:86)
        at net.sf.jasperreports.engine.fill.JRBaseFiller.<init>(JRBaseFiller.java:111)
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.<init>(JRVerticalFiller.java:69)
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.<init>(JRVerticalFiller.java:57)
        at net.sf.jasperreports.engine.fill.JRFiller.createBandReportFiller(JRFiller.java:219)
        at net.sf.jasperreports.engine.fill.JRFiller.createReportFiller(JRFiller.java:234)
        at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:134)
        at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:667)
        at net.sf.jasperreports.engine.JasperFillManager.fillReport(JasperFillManager.java:983)
        at de.cenote.jasperstarter.Report.fill(Report.java:237)
        at de.cenote.jasperstarter.App.processReport(App.java:217)
        at de.cenote.jasperstarter.App.main(App.java:102)
PHP Notice:  Undefined offset: 0 in C:\xampp\htdocs\DS_dev_02\vendor\geekcom\phpjasper-laravel\src\PHPJasper.php on line 222
```

How can I remedy this? I'm running Laravel 5.5 with PHP7 on XAMPP. Thanks in advance.

**Comment by geekcom** [comment]
Hi @hondaman900 , thanks for use PHPJasper, unfortunately I haven't tested support for java 10, I will try to solve this soon.

**Comment by hondaman900** [comment]
@geekcom 

I installed Java JRE8 and opted for it to remove prior versions, and it now works, at least in Tinker. Now I just have to figure out how to have my app produce the report to my app pages, and offer the user option to download one of the files formats such as PDF or RTF.

Thanks for the quick response  :)

**Comment by geekcom** [comment]
Great @hondaman900 , see the docs for this
